### ISSUE TITLE
"Undefined variable: choices" When trying to switch to different mailbox

### ISSUE THREAD

**Issue by devanlooches** [soywod/himalaya.vim#6]
Hello,
Sorry to bother you with another issue but I am getting this error when I try to switch to a different mailbox (pressing gm):

```
Vim(let):E121: Undefined variable: choices
```
Any idea how to fix it?
Thanks in Advance.

**Comment by soywod** [comment]
My bad, there was a typo (https://github.com/soywod/himalaya.vim/blob/52912cdab36911f09832a7cfffc15c7fe1ba3150/autoload/himalaya/mbox.vim#L35-L45). Should have been `choice` instead of `choices`. It's been a while I didn't test this piece of code, since I use [`fzf`](https://github.com/junegunn/fzf) instead. I just fixed, it will be merged on master with the next CLI release!
